### ISSUE TITLE
Updates cause all siblings to update

### ISSUE THREAD

**Issue by mindplay-dk** [yisar/fre#73] opened 2019-10-13 11:04 UTC
I've noticed another problem with reconciliation.

It looks like updates (e.g. triggered by `setState` via a `useState` hook) cause not only the affected component to update, but the entire range of sibling components after to it.

![image](https://user-images.githubusercontent.com/103348/66714640-58705400-edb9-11e9-977a-c8da62a32a2e.png)

Only the sibling components *after* the affected component get updated - siblings *before* the affected component do not.

So, if you update counter 1, counters 2 and 3 also updates. If you update counter 2, counter 3 also updates. If you update counter 3, only counter 3 updates.

You can try it here:

https://codesandbox.io/s/fre-demo-uxuic

I will try to add a test-case to catch this issue.

**Comment by 132yse** [comment] 2019-10-13 11:46
I see the use case, which looks like a bug. I may know where the problem is and I will fix it as soon as possible 😭

**Comment by 132yse** [comment] 2019-10-13 14:08
I have fixed this bug, now it works well~

**Comment by mindplay-dk** [comment] 2019-10-13 16:47
Looks good. 👍

I've been trying to write a test for this, and I don't know know how to.

I have a preliminary test on [this branch](https://github.com/132yse/fre/compare/master...mindplay-dk:sibling-updates), but it doesn't work. You see the lines with `// ???` next to them? I need to make `content` optional, so that `testUpdates` only performs an update if you give it `content`.

The problem is `testUpdates` currently relies on the `render`-callback to know when the update is complete. The `render`-callback is fine for many of the tests, but not for this one - in this case, we don't want a full update of the `content`, we just want to know as soon as the scheduler runs out of work.

The problem is, this feature isn't useful for applications - it's *only* useful for testing. We probably don't want a feature in the library that exists only for tests? We want to keep the library small.

I thought about trying something like this:

```js
import { getWIP } from "../src/reconciler"

const idleCallbacks = []

function onIdle(callback) {
  idleCallbacks.push(callback)
  checkIdle()
}

function checkIdle() {
  if (idleCallbacks.length === 0) {
    return // no callbacks waiting
  }

  if (getWIP()) {
    setTimeout(checkIdle, 10)
  }
}
```

The idea here is tests can ask for a notification as soon as there are no updates queued. So I'd be able to do a call to a `useState` setter to trigger an update, and then immediately ask for an `onIdle` notification so I know when the update has finished.

The problem is, you recently [changed](https://github.com/132yse/fre/commit/be2e5b3bd71306c655d83931d983b50d7872ede3#diff-6c01e01c99de92174435ee504d707af0R205) `getWIP`, which now returns an empty object if there's no work in progress? (and I don't understand why you need the empty object.)

But is there some other way I can check if the queue is empty?

**Comment by 132yse** [comment] 2019-10-13 23:32
I don't know if it's feasible for you to use WIP if you want to get the rest of the work. I think it's enough for us to test the dom.
I will refactor the logic of hooks and, if possible, remove empty objects.

**Comment by mindplay-dk** [comment] 2019-10-14 09:28
> I don't know if it's feasible for you to use WIP if you want to get the rest of the work. I think it's enough for us to test the dom.

The problem is it's all async and scheduled - so the test can't actually know *when* to test the DOM, when it's safe to proceed to the next step of the test, and so on.

Take a closer look at `testUpdates` and maybe this will help you understand - it's using the `render`-callback right now to know when the first update has finished, and it's using a "dummy" wrapper-component with `useEffect` to know when updates have finished. This approach only works for a full tree update, and that's fine for most of the tests - but for the sibling update tests, we want to count updates of specific sibling components, so a full tree update won't work.

We need some way to check if any work is currently scheduled.

Let me know if you can think of a good way to do that?

**Comment by 132yse** [comment] 2019-10-15 01:24
@mindplay-dk 
I've perfected the test, and now reconciler's test is completely covered
The rest is the scheduler test, which is task scheduling and can be tested with ordinary tasks.

**Comment by mindplay-dk** [comment] 2019-10-15 10:44
Was this change on purpose?

![image](https://user-images.githubusercontent.com/103348/66824812-51784b80-ef49-11e9-8f17-727818820948.png)

I don't understand what that's for? An empty `<div>` and then you just remove it without testing anything? 🤔

**Comment by 132yse** [comment] 2019-10-15 10:53
It's not that without testing, it's test that keys are still valid when elements with keys have slibings  without keys.

**Comment by mindplay-dk** [comment] 2019-10-15 11:07
> It's not that without testing, it's test that keys are still valid when elements with keys have slibings without keys.

Ah, I see 😊

But this test only shows that we end up with the correct result - it doesn't prove that there are no unnecessary updates. (Having code-coverage in this case doesn't prove anything, because the test is trying to prove that something *doesn't* execute.)

Did you look at [this test](https://github.com/132yse/fre/compare/master...mindplay-dk:sibling-updates)? That's the one I'm trying to fix.

That's why I've been asking about a way to check if there's any work in the queue.

**Comment by 132yse** [comment] 2019-10-15 11:51
I seem to understand your test case. It seems to be wrong.
[here](https://github.com/132yse/fre/compare/master...mindplay-dk:sibling-updates#diff-98d6239b4197855a4e3ad7e1c16979a3R314)
The content is null because the [workloop](https://github.com/132yse/fre/blob/master/src/reconciler.js#L38) is not over.
What do you want to test here? Do you want to test slibing components rerendering?

**Comment by 132yse** [comment] 2019-10-15 12:05
I have a idea, such as
```js
function A(){
  const [count,setCount] = useState(0)
  return (
    <div>{count}</div>
  )
}
```
```js
function B(){
  useEffect(()=>{
    document.querySelector('.count').innerHtml = new Date().toString()
  })
  return (
    <div class="count">0</div>
  )
}
```
We operate DOM in component B and then check whether the DOM operation is valid at the time of the second rendering.

**Comment by mindplay-dk** [comment] 2019-10-15 19:32
Here's what I'd like to be doing:

```jsx
  await testUpdates([
    {
      content,
      test: ([div]) => {
        expect(numUpdates.a).toBe(1)
        expect(numUpdates.b).toBe(1)
        update.a()
      }
    },
    {
      content: null,
      test: ([div]) => {
        expect(numUpdates.a).toBe(2)
        expect(numUpdates.b).toBe(1)
        update.b()
      }
    },
    {
      content: null,
      test: ([div]) => {
        expect(numUpdates.a).toBe(2)
        expect(numUpdates.b).toBe(2)
      }
    }
  ])
```

So `update.a()`, for example, is what triggers the update of `numUpdates.a`, so we can check how many times the two component instances were rendered.

This wouldn't work right now, since `content: null` is not supported by `testUpdates`.

So, in `testUpdates`, I currently use a [wrapper component](https://github.com/132yse/fre/blob/master/test/render.test.jsx#L15-L23) that triggers an effect, which tells me the tree has been updated.

I still think we need a way to "ask" the reconciler or scheduler if they have any work in the queue? There must be some way we can do that?

**Comment by 132yse** [comment] 2019-10-15 23:36
Your idea is wrong. You can only test the rendering results of DOM, and you can't check whether there is any work rest, because when there is any work rest, it will enter an infinite loop until the work is exhausted.

**Comment by mindplay-dk** [comment] 2019-10-17 16:24
I think the idea is right. It's not an infinite loop - the scheduler stops when the work is exhausted; all I need is a way to know when the work loop rests.

This would simplify testing and make it somewhat simpler - right now, I need to use a dummy wrapper component and an effect to make `testUpdates` work, which is totally different from how `testRender` works. Most of that code could be removed, and it makes the tests somewhat safer, since it guarantees that there is really no more work in the queue. (which is an assumption right now - technically, an effect, for example, could trigger a `useState` setter, queueing another callback, and you wouldn't be able to test that now... we don't happen to have any tests like that yet, but we also don't have full coverage yet, and there's a lot of things left to test, not least combinations of effects/memo/state mixed together...)

My first idea with the extra wrapper-component was meant as a temporary fix to get the tests started, so I'd really like to solve this...

**Comment by yisar** [comment] 2019-12-24 09:53
We already have tests about async update[here](https://github.com/yisar/fre/blob/master/test/update.test.js), I'll close it first.

**Closed by yisar** 2019-12-24 09:53 UTC
